name: Increment Build

on: 
    push:
        branches:
            - main  
    
jobs:

  increment-build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    # Increments the build number when a push is made
   
    steps:
    - uses: actions/checkout@v2            
        
    # Increment the Build
    
    - name: Increment BUILD
      run:  sh ./.increment_build.sh 
      
    - name: Sets BUILD
      run:  'echo ::set-env name=BUILD::$( cat build )'
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'      

    - uses: stefanzweifel/git-auto-commit-action@v4.0.0     
      with:
        commit_message: Build ${{ env.BUILD }}
        branch: ${{ github.head_ref }}   
        commit_user_name: retro-bot
        commit_user_email: retro@bot.org
        commit_author: RetroSeller GitBot <retro@bot.org> 
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'        